version: "3.1"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/
      - $HOME/docker-data/liulidao-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - $HOME/docker-data/liulidao-redis:/data

volumes:
  postgres:
